<?php
    include_once "layout/header.layout.phtml";
?>
    <div style="max-width: 550px; width: 100%; margin: 2em auto" >
        <div class="panel panel-default">
            <div class="panel-heading">Ingreso de Usuarios</div>
            <div class="panel-body">
                <div>
                    <?php
                        if(isset($_GET["login"]) && is_string($_GET["login"]) &&  !$_GET["login"]){
                            echo "Ocurrio un error al ingresar al sistema.";
                        }
                    ?>
                </div>
                <form action="autenticar.php" method="post" class="form-horizontal" role="form">
                    <div class="form-group">
                      <label for="inputEmail1" class="col-lg-2 control-label">Usuario</label>
                      <div class="col-lg-10">
                        <input type="text" name="usuario" class="form-control" id="inputEmail1" placeholder="Usuario" required>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="inputPassword1" class="col-lg-2 control-label">Contraseña</label>
                      <div class="col-lg-10">
                        <input type="password" name="clave" class="form-control" id="inputPassword1" placeholder="Contraseña" required>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-lg-offset-2 col-lg-10">
                        <button type="submit" class="btn btn-success">Ingresar</button>
                      </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<?php
    include_once "layout/footer.layout.phtml";
?>