<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Gestión de la Empresa</h3>
    </div>
    <div class="panel-body">
        <div>
            <ul id="empresaTAB" class="nav nav-tabs">
                <li class="active"><a href="#empresa">Empresa</a></li>
                <li><a href="#sucursales">Sucursales</a></li>
                <li><a href="#departamentos">Departamentos</a></li>
                <li><a href="#area">Area</a></li>
                <li><a href="#cargo">Cargo</a></li>
                <li><a href="#empleado">Empleados</a></li>
            </ul>
            
            <div id="myTabContent" class="tab-content">
                <div class="tab-pane fade active in" id="empresa">a</div>
                <div class="tab-pane fade" id="sucursales">b</div>
                <div class="tab-pane fade" id="departamentos">c</div>
                <div class="tab-pane fade" id="area">d</div>
                <div class="tab-pane fade" id="cargo">e</div>
                <div class="tab-pane fade" id="empleado">f</div>
            </div>
            
            
        </div>
    </div>
</div>

<script>
    $('#empresaTAB a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
    });
</script>