<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Análisis Gap</h3>
    </div>
    <div class="panel-body">
        <div style="border-bottom:1px solid #ccc; margin-bottom: 1em; padding-bottom: 1em;">
            <div class="btn-group btn-group-sm" >                
                <button id="btnAnalisisGapExpandir" type="button" data="true" class="btn btn-default"><span class="glyphicon glyphicon-resize-full"></span> Expandir</button>
                <button id="btnAnalisisGapContraer" type="button" data="false" class="btn btn-default"><span class="glyphicon glyphicon-resize-small"></span> Contraer</button>
                <button id="btnAnalisisGapDescargar" type="button" class="btn btn-default"><span class="glyphicon glyphicon-download-alt"></span> Descargar</button>
                <button id="btnAnalisisGapGrafica" type="button" class="btn btn-default"><span class="glyphicon glyphicon-picture"></span> Mostrar Gráficas</button>
                <button id="btnAnalisisGapLineaTiempo" type="button" class="btn btn-default"><span class="glyphicon glyphicon-stats"></span> Linea de Tiempo</button>
            </div>
        </div>
        
        <div id="analisisGAP">
            <table id="datagridAnalisisGAP"  class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th>Seccion</th>
                        <th>Control</th>
                        <th>Aplica</th>
                        <th>Estado</th>
                        <th>Observación</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<!-- modal -->
<div  class="modal fade" style="" id="modalGraficaGap" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="width:800px">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Analisis GAP - Gráficas</h4>
      </div>
      <div class="modal-body">
        <div id="graficasGAP">
            <div id="graficasGAPEstadoControles"></div>
            <div id="graficasGAPEstadoControlesSeccionI" style=""></div>            
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div  class="modal fade" style="" id="modalAnalisisGapLineaTiempo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="width:90%">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Analisis GAP - Línea de Tiempo</h4>
      </div>
      <div class="modal-body">
        <form id="formLineaTiempoGapControl" class="form-inline" role="form">
          <div class="form-group">
            <label class="sr-only" for="cboControlesLineaTiempo">Control</label>
            <select class="form-control" id="cboControlesLineaTiempo">
            </select>
          </div>
          <button type="submit" class="btn btn-primary">Procesar</button>
        </form>

        <div id="lineaTiempoGAP" style="margin-top:10px;">
            <table class="table table-striped table-hover table-condensed ">
                <thead>
                    <th>#</th>
                    <th>Indice</th>
                    <th>Detalle</th>
                    <th>Control</th>
                    <th>Valor Inicial</th>
                    <th>Valor Actualizado</th>
                    <th>Fecha y Hora</th>
                </thead>
                <tbody></tbody>
            </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
        
<script src="./static/js/highcharts.js"></script>
<script src="./static/js/exporting.js"></script>
<script>
    /*** LOADS ***/
    AnalisisGapConsultar();

    /*** EVENTOS ***/
    $("button#btnAnalisisGapExpandir, button#btnAnalisisGapContraer").click(AnalisisGapConsultar);
    $("button#btnAnalisisGapGrafica").click(crearGraficaGap);
    $("button#btnAnalisisGapLineaTiempo").click(crearLineaTiempoGap);

    $("form#formLineaTiempoGapControl").submit(function(e){
        e.preventDefault();
        var data = $("select#cboControlesLineaTiempo").val();
        $.get("./ajax/inicio/analisis_gap_bitacora_consultar.ajax.php",{control:data},function (r) {
            $("#lineaTiempoGAP table tbody").html(r);
        });
    });

    /*** FUNCIONES ***/

    function AnalisisGapConsultar(){
            var expandir = $(this).attr('data') || false;
            $.get("./ajax/inicio/analisis_gap_consultar.ajax.php", { expandir: expandir }, function(r){
                $("table#datagridAnalisisGAP tbody").html(r);
            });
    }

    function crearLineaTiempoGap(){
        $.get("./ajax/inicio/analisis_gap_consultar_combo.ajax.php", function(r){
            $("select#cboControlesLineaTiempo").html(r);
        });
        $("#lineaTiempoGAP table tbody").html("");
        $("#modalAnalisisGapLineaTiempo").modal("show");
    }

    function crearGraficaGap(){
        $.getJSON("./ajax/inicio/analisis_gap_totales_control_por_dominio.ajax.php",{},function(r){
            var categorias = [], totales = [], no_definido = [], no_implementado = [], parcialmente_implementado = [], implementado = [], promedio = [];
            for(var i in r){
                categorias.push(r[i].indice);
                totales.push(parseFloat(r[i].total));
                no_definido.push(parseFloat(r[i].no_definido) * 100 / parseFloat(r[i].total));
                no_implementado.push(parseFloat(r[i].no_implementado) * 100 / parseFloat(r[i].total));
                parcialmente_implementado.push(parseFloat(r[i].parcialmente_implementado) * 100 / parseFloat(r[i].total));
                implementado.push(parseFloat(r[i].implementado) * 100 / parseFloat(r[i].total) );
                //promedio.push(parseFloat(r[i].promedio));
            }
            for (var i=0; i<=categorias.length; i++) {
                
                promedio.push((no_definido[i]+no_implementado[i]+parcialmente_implementado[i]+implementado[i])/4);
            }
                
                console.log(promedio);
             $('#graficasGAPEstadoControlesSeccionI').highcharts({
                    chart: {
                        //type: 'column'
                        width: 730
                    },
                    title: {
                        text: 'Estado de controles GAP por Secciones I'
                    },
                    subtitle: {
                        text: ''
                    },
                    xAxis: {
                        categories: categorias,
                        labels: {
                            rotation: -45,
                            align: 'right'
                        }
                    },
                    yAxis: {
                        min: 0,
                        title: {
                            text: 'Estado (%)'
                        }
                    },
                    tooltip: {
                        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                            '<td style="padding:0"><b>{point.y:.1f} %</b></td></tr>',
                        footerFormat: '</table>',
                        shared: true,
                        useHTML: true
                    },
                    plotOptions: {
                        column: {
                            pointPadding: 0.2,
                            borderWidth: 0,
                            stacking: 'percent'
                        }
                    },
                    series: [{
                        type: 'column',
                        name: 'No definido',
                        data: no_definido
            
                    }, {
                        type: 'column',
                        name: 'No implementado',
                        data: no_implementado
            
                    }, {
                        type: 'column',
                        name: 'Parcialmente Implementado',
                        data: parcialmente_implementado
            
                    }, {
                        type: 'column',
                        name: 'Implementado',
                        data: implementado
            
                    }
                    /*,{
                        type: 'spline',
                        name: 'Promedios',
                        data: promedio,
                        marker: {
                            lineWidth: 2,
                            lineColor: Highcharts.getOptions().colors[2],
                            fillColor: 'white'
                        }
                    }*/]
                });
        });

        $.getJSON("./ajax/inicio/analisis_gap_totales_control.ajax.php",{},function(r){
            //console.log(r.total);
            var total = parseInt(r.total),
                implementado = parseInt(r.implementado),
                parcial = parseInt(r.parcialmente_implementado),
                no = parseInt(r.no_implementado),
                nodefinido = parseInt(r.no_definido);
                
                //$('#graficasGAP').toggle();

                $('#graficasGAPEstadoControles').highcharts({
                    chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    width: 730
                        },
                        title: {
                            text: 'Estado de los Controles'
                        },
                        tooltip: {
                            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                        },
                        plotOptions: {
                            pie: {
                                allowPointSelect: true,
                                cursor: 'pointer',
                                dataLabels: {
                                    enabled: true,
                                    color: '#000000',
                                    connectorColor: '#000000',
                                    format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                                },
                                showInLegend: true
                            }
                        },
                        series: [{
                            type: 'pie',
                            name: 'Browser share',
                            data: [
                                ['No definido',   nodefinido*total/100],
                                ['No implementado',      no*total/100],
                                ['Parcialmente implementado',    parcial*total/100],
                                ['Implementado',    implementado*total/100]
                            ]
                        }]
                });

        });
        
        $("#modalGraficaGap").modal("show");
    }

</script>