<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Objetivos del Negocio</h3>
    </div>
    <div class="panel-body">
        <?php
            if((!isset($_GET["acta"]) && empty($_GET["acta"]))){
            $acta = 0;
                if(!isset($_GET["objetivo"])  && empty($_GET["objetivo"])){
        ?>
        <div style="display: block; overflow: hidden">
            <div class="form-group">
                <label for="cboActaReunion" class="col-lg-2 control-label">Acta Reunión</label>
                    <div class="col-lg-10">
                <select class="form-control input-sm" id="cboActaReunion" name="cboActaReunion" required >
                    <option value="">-- Seleccione un acta reunion --</option>
                    <?php
                        $query_acta_reunion = $objActaReunion->ConsultarActas();
                        while($reg = $query_acta_reunion->fetchObject()){
                            echo '<option value="'.$reg->idacta_reunion.'"';
                                if(isset($_GET["acta"]) && !empty($_GET["acta"]) && is_numeric($_GET["acta"])){
                                    if($reg->idacta_reunion == $_GET["acta"]){ echo " selected "; }
                                }
                            echo '>'.$reg->asunto.'</option>';
                        }
                    ?>
                </select>
                </div>
            </div>
            
        </div>
        <?php }else {  require_once "objetivo-sg-editar.view.phtml"; }?>
        <?php }else{ $acta = $_GET["acta"];  ?>
        <div style="border-bottom:1px solid #ccc; margin-bottom: 1em; padding-bottom: 1em;">
            <div class="btn-group btn-group-sm">
                <button id="btnObjetivoAtras" type="button" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span> Volver atras</button>
                <button id="btnObjetivoNuevo" type="button" class="btn btn-default"><span class="glyphicon glyphicon-file"></span> Nueva Objetivo</button>
                <button id="btnObjetivoActualizar" type="button" class="btn btn-default"><span class="glyphicon glyphicon-refresh"></span> Actualizar</button>
                <button id="btnObjetivoEliminar" type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span> Eliminar</button>
            </div>
        </div>
        
        <div id="dataGridObjetivos">
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th>Objetivo</th>
                        <th>Fecha</th>
                        <th>Descripción</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        $query_objetivos = $objObjetivo->ConsultarObjetivos($_GET["acta"]);
                        while($reg = $query_objetivos->fetchObject())
                        {
                            $pag = $_GET["pag"];
                            echo '<tr><td><a href="?pag='.$pag.'&objetivo='.$reg->idobjetivo.'">'.$reg->objetivo.'</a></td><td>'.$reg->fecha.'</td><td>'.$reg->descripcion.'</td><td><input type="checkbox" name="objetivos[]" value="'.$reg->idobjetivo.'"></td></tr>';
                        }
                    ?>
                </tbody>
            </table>
        </div>
        
        <?php } ?>
    </div>
</div>

<script>
    $(document).on("ready", function(){
        $("button#btnObjetivoAtras").click(function(){ history.back(); });
        $("button#btnObjetivoNuevo").click(ObjetivoNuevo);
        $("button#btnObjetivoActualizar").click(ObjetivoActualizar);
        $("button#btnObjetivoEliminar").click(ObjetivoEliminar);
        
        $("select#cboActaReunion").change(function(){
            var acta = $(this).val(),
                url  = document.URL+"&acta="+acta;
            if (acta) {
                document.location.href = url;
            }            
        });
        
        function ObjetivoNuevo() {
            $.post("./ajax/inicio/objetivo_nuevo.ajax.php", { acta:<?=$acta?> }, function(r){
                ObjetivoActualizar();
            });
        }
        
        function ObjetivoEliminar() {
            $("input[type=checkbox]:checked").each(function(index, val){
                $.post("./ajax/inicio/objetivo_eliminar.ajax.php", { objetivo: val.value }, function(r){
                    
                });
            });
            ObjetivoActualizar();
        }
        
        function ObjetivoActualizar() {
            $.get("./ajax/inicio/objetivo_consultar.ajax.php", { pag : '<?php echo $_GET["pag"]; ?>', acta: <?=$acta?> }, function(r){
                $("div#dataGridObjetivos table tbody").html(r);
            });
        }
    });
</script>