<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Calendario de Proyecto</h3>
    </div>
    <div class="panel-body">
    	<div style="border-bottom:1px solid #ccc; margin-bottom: 1em; padding-bottom: 1em;">
            <select name="cboMostrarCalendario" id="cboMostrarCalendario" class="form-control"  style="width:250px;display:inline-block;">
            	<!--<option value="inicio-fin">Mostrar Inicio y Fin de Tareas</option>-->
            	<option value="inicio">Mostrar solo Inicio</option>
            	<option value="fin">Mostrar solo Fin</option>
            </select>
            <select name="cboAnoCalendario" id="cboAnoCalendario" class="form-control"  style="width:150px;display:inline-block;">
            	<option value="2011">2011</option>
            	<option value="2012">2012</option>
            	<option value="2013">2013</option>
            </select>
            <select name="cboMesCalendario" id="cboMesCalendario" class="form-control" style="width:200px;display:inline-block;">
            	<option value="01">Enero</option>
            	<option value="02">Febrero</option>
            	<option value="03">Marzo</option>
            	<option value="04">Abril</option>
            	<option value="05">Mayo</option>
            	<option value="06">Junio</option>
            	<option value="07">Julio</option>
            	<option value="08">Agosto</option>
            	<option value="09">Setiembre</option>
            	<option value="10">Octubre</option>
            	<option value="11">Noviembre</option>
            	<option value="12">Diciembre</option>
            </select>

            <button type="button" id="btnProcesarCalendario" class="btn btn-success">Procesar</button>
    	</div>
    	<div id="dataCalendario" >

    	</div>
	</div>
</div>

<script>
	$("button#btnProcesarCalendario").click(function(){
		var data = { mostrar : $("select#cboMostrarCalendario").val(),
					 ano     : $("select#cboAnoCalendario").val(),
					 mes     : $("select#cboMesCalendario").val() 
					};
		$.get("./ajax/inicio/proyecto_calendario_consultar.ajax.php", data, function(r){
			$("div#dataCalendario").html(r);
		});
	});

</script>