<div class="panel panel-default">
    <div class="panel-heading">
     	<h3 class="panel-title">Gestión del Proyecto</h3>
    </div>
    <div class="panel-body">
    <?php if(isset($_GET["tarea"]) && !empty($_GET["tarea"]) && is_numeric($_GET["tarea"])){ require_once "proyecto-gestion-editar.view.phtml";  }else{ ?>
     	<div style="border-bottom:1px solid #ccc; margin-bottom: 1em; padding-bottom: 1em;">
            <div class="btn-group btn-group-sm">
                <button id="btnGestionProyectoNuevaTarea" type="button" class="btn btn-default" disabled><span class="glyphicon glyphicon-file"></span> Nueva tarea</button>
                <button id="btnGestionProyectoEliminarTarea" type="button" class="btn btn-default" disabled><span class="glyphicon glyphicon-refresh"></span> Eliminar tarea</button>
                <button id="btnGestionProyectoCrearHistorico" type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span> Crear historico</button>
                <button id="btnGestionProyectoDescargar" type="button" class="btn btn-default"><span class="glyphicon glyphicon-download-alt"></span> Descargar</button>
            </div>
            <input type="hidden" name="txtIdObjetivoHelpper" id="txtIdObjetivoHelpper" />
            <input type="hidden" name="txtIdObjetivoDetalleHelpper" id="txtIdObjetivoDetalleHelpper" />
            <div style="max-width:300px;width:100%;margin-top:10px;" class="pull-right">
            	<div class="progress progress-striped active" style="height:15px; margin:0;">
				  	<div id="progressbarAvanceProyecto" class="progress-bar progress-bar-success"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100">
				    <span class="sr-only">45% Complete</span>
				  </div>
				</div>
            </div>
        </div>

        <div>
        <?php
        	$query_dominios = $objGap->ConsultarDominios();
        ?>
        	<table class="table">
        		<thead>
        			<th></th>
        			<th>Detalle</th>
        			<th>Responsable</th>
        			<th>Dias Restantes</th>
        			<th>Fecha Inicio</th>
        			<th>Fecha Fin</th>
        		</thead>
        		<tbody>
        		<?php
        		$i= 1;
        		$class = "";
        		while ($reg = $query_dominios->fetchObject()) {
        			if($i%2){ $class = "active";} else{ $class = ""; }
        			echo '<tr class="dominio '.$class.'">
        					<td><span class="dominio-detalle" data-id="'.$reg->id.'" data-estado="comprimido"><img src="./static/img/plus.gif" /></span></td>
        					<td>'.$reg->indice.' - '.$reg->detalle.'</td>
        					<td></td>
        					<td></td>
        					<td></td>
        					<td></td>
        				</tr>';
        				$i++;
        		}
        		?>
        		</tbody>
        	</table>	
        </div>
        <?php } ?>
    </div>
</div>

<script>
	CalcularAvanceDeProyecto();

	$("button#btnGestionProyectoNuevaTarea").click(GestionProyectoNuevaTarea);


	function GestionProyectoNuevaTarea(){
		var data = { objetivo : $("input#txtIdObjetivoHelpper").val() };
		$.post("./ajax/inicio/proyecto_nueva_tarea.ajax.php", data, function(r){
			console.log(r);
			//$("tr.dom, tr.tarea").slideUp();
			//ConsultarTareasDeObjetivos();
			location.reload();
		});
	};

	function CalcularAvanceDeProyecto(){
		$.get("./ajax/inicio/proyecto_avance_tarea.ajax.php", function(r){
			var data = JSON.parse(r);
			$("div#progressbarAvanceProyecto").css("width",data.avance+"%");
		})
	}

	function ConsultarTareasDeObjetivos(){
		var data = { objetivo: $("input#txtIdObjetivoHelpper").val() };
		$.get("./ajax/inicio/proyecto_consultar_tareas_detalles.ajax.php", data, function(r){
			var padreHelpper = $("input#txtIdObjetivoDetalleHelpper").val();
			var padre = $("tr."+padreHelpper);
			console.log(padre);
		});
	}

	$("tr td span.dominio-detalle").click(function(){
        var tr = $(this);        	
        var dominio = $(this).attr('data-id');
        var estado = $(this).attr('data-estado');
        
        if(estado.toString() == "comprimido"){
            $(this).attr('data-estado', "expandido");
            $(this).html('<img src="./static/img/minus.gif" />');
            $.post("./ajax/inicio/proyecto_consultar_dominio_detalles.ajax.php", { dominio: dominio }, function(r){
                $(r).insertAfter(tr.parents('tr'));
            });
        }else{
            tr.attr('data-estado', "comprimido");
            //tr.parents('tr').next().remove();
            console.log("tr.dom"+dominio);
            $(this).html('<img src="./static/img/plus.gif" />');
            $("tr.dom"+dominio+", tr.tarea"+dominio).hide();
        }

        console.log(padre);
    });


</script>
